
export const NEW_INVOICE_REQUEST = "NEW_INVOICE_REQUEST";
export const NEW_INVOICE_SUCCESS = "NEW_INVOICE_SUCCESS";
export const NEW_INVOICE_FAIL = "NEW_INVOICE_FAIL";



export const ALL_INVOICE_REQUEST = "ALL_INVOICE_REQUEST";
export const ALL_INVOICE_SUCCESS = "ALL_INVOICE_SUCCESS";
export const ALL_INVOICE_FAIL = "ALL_INVOICE_FAIL";

export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';


export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
// export const ALL_INVOICE_SUCCESS = "ALL_INVOICE_SUCCESS";
// export const ALL_INVOICE_FAIL = "ALL_INVOICE_FAIL";
